List<Lead> leadToInsertList = new List<Lead>();
leadToInsertList.add(new Lead(LastName = 'Lead 1', Company = 'SoftInnovas'));
leadToInsertList.add(new Lead(LastName = 'Lead 2', Company = 'SoftInnovas'));
leadToInsertList.add(new Lead(LastName = 'Lead 3', Company = 'SoftInnovas'));
leadToInsertList.add(new Lead(LastName = 'Lead 4', Company = 'SoftInnovas'));
leadToInsertList.add(new Lead(LastName = 'Lead 5', Company = 'SoftInnovas'));
insert leadToInsertList;